// Shadcn UI components are auto-generated by running:
// npx shadcn@latest add button card badge table tabs dialog
// This file is a placeholder – run the commands in README.md to generate them.
export {};
